Tugas_2_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import update_status.urls as update_status
import halaman_riwayat.urls as halaman_riwayat
import page_profile.urls as page_profile
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status,namespace='update-status')),

    url(r'^page_profile/', include(page_profile,namespace='page-profile')),
    # url(r'^$', RedirectView.as_view(url='page_profile/',permanent=True),name='$'),

    url(r'^halaman_riwayat/', include(update_status,namespace='halaman-riwayat')),

    url(r'^$', RedirectView.as_view(url='update_status/',permanent=True),name='$'),

]

my_profile/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # index dan dashboard
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import *
from page_profile.views import edit_profile
#import view profile


from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'^dashboard/edit_profile', edit_profile, name='edit_profile'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^add_status/', add_status, name='add_status'),
    url(r'^delete/(?P<id>\d+)/', delete_status, name='delete'),
]

update_status/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))
    updated_at = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

class Status(models.Model):
    pengguna = models.ForeignKey(Pengguna)
    status = models.CharField(max_length=1000)
    created_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

    def as_dict(self):
        return {
            "status": self.status,
            "created_date": self.created_date,
        }
        
class Comment(models.Model):
	pengguna = models.ForeignKey(Status,on_delete=models.CASCADE)
	comment = models.CharField(max_length=1000)
	created_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        
    }
    status_attrs = {
        'type': 'text',
        'cols' : 149,
        'rows' : 4,
        'class' : 'status-form-input',
        'placeholder' : 'Apa yg anda pikirkan?'
    }

   
    status = forms.CharField(label='',widget=forms.Textarea(attrs=status_attrs), required=True)

update_status/views.py
from __future__ import unicode_literals

import json
from .forms import Status_Form
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
import pytz
from datetime import *
from .models import Pengguna, Status, Comment
from halaman_riwayat import views 
from django.core import serializers

response = {}
def index(request):
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('update-status:dashboard'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        html = 'update_status/login.html'
        return render(request, html, response)


def dashboard(request):
	if 'user_login' not in request.session:
		response['author'] = get_data_user(request, "user_login")
		html = 'update_status/login.html'
		return render(request, html, response)
	else:
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		try:
			pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
		except Exception as e:
			pengguna = create_new_user(request)
		response['Status_form'] = Status_Form
		kode_identitas = get_data_user(request,'kode_identitas')
		pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
		response['status'] = pengguna.status_set.all().order_by('-id')
		response['daftar_riwayat'] = views.get_daftar_riwayat()
		# print(response['status'])
		# stat = Status.objects.all().order_by('-id')
		stat = pengguna.status_set.all().order_by('-id')
		if (len(stat) > 0):
			message = stat[0]
			newMessage = message.status
			time = message.created_date
		else:
			newMessage = "You have not posted yet" 
			time = date(datetime.now().year,datetime.now().month,datetime.now().day)
		# response['headline'] = response.session['link']
		response['jumlah_status'] = pengguna.status_set.count()
		response['latestMessage'] = newMessage
		html = 'update_status/dashboard.html'
		return render(request, html, response)

def add_status(request):
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'], pengguna=pengguna)
		status.save()
	return HttpResponseRedirect(reverse('update-status:dashboard'))

def delete_status(request, id):
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
	status = pengguna.status_set.filter(pk=id)
	status.delete()
	return HttpResponseRedirect(reverse('update-status:dashboard'))


def get_data_user(request, tipe):
    data = None
    if tipe == "user_login" and 'user_login' in request.session:
        data = request.session['user_login']
    elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
        data = request.session['kode_identitas']

    return data

def create_new_user(request):
    nama = get_data_user(request, 'user_login')
    kode_identitas = get_data_user(request, 'kode_identitas')

    pengguna = Pengguna()
    pengguna.kode_identitas = kode_identitas
    pengguna.nama = nama
    pengguna.save()

    return pengguna


def set_data_for_session(request):
    response['author'] = get_data_user(request, 'user_login')
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

templates/update_status/dashboard.html
{% extends "lab_10/layout/base.html" %}

{% block content %}
<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
<style type="text/css">
.font1{
    font-family: 'Spectral SC', serif;
}
.part2-info_user .glyphicon-user{
	font-size: 150px;
    color: red
}
.buttonPertama{
	margin-bottom: 20px;
}
.myData{
	
	padding: 10px;
}
.part2 a{
	margin-bottom: 30px;
	margin-left: 30px;
}
.part2_info_user{
	background-color: #C8D8DE;
	padding: 10px;
	border-radius: 10px;
}
.media-left .glyphicon-user{
font-size: 50px;
margin-right: 30px;
}
.kotak{
background-color: #e6e6e6;
border-radius: 10px;
margin-bottom: 20px;
}
.page1{
    top: -120px;
}
.row .btn-danger{
    margin-top: 40px;
}
</style>
<div class="container page1">
	<div class="col-md-8 font1"><h1>Selamat datang {{ author }}</h1></div>
	
	<div class="col-md-4">
		<a href="{% url 'update-status:auth_logout' %}" class="btn btn-danger btn-lg" onclick="return confirm('Keluar?')">Logout </a>
	</div>
</div>
<div class="container part2">
	<div class="col-md-4 part2_info_user">
		<span class="glyphicon glyphicon-user pull-left" style="font-size:150px;"></span>
		<a href="#" class="btn btn-lg btn-info ">Lihat Forum</a>
		<a href="#" class="btn btn-lg btn-default">Update Status</a>
	</div>
	<div class="col-md-4">
		<h2 class="font1">Jumlah Status : {{jumlah_status}}</h2>
		<h2 class="font1">Last Comment : {{ latestMessage }}</h2>
	</div>
	<div class="col-md-4"></div>
</div>

<div class="container part3">
<form id="form" method="POST" action="{% url 'update-status:add_status' %}">
                    <h2><strong>Input Status..</strong></h2>
                    {% csrf_token %}
                    {{ Status_form }}
                    <br><input id="submit" type="submit" class="btn btn-md btn-info" value="Submit">
                    <br><br>
                </form>
</div>
<!-- show status -->
<section name="my-list" id="my-list" style="padding-bottom: 20px">
    {% if status %}
    <div class="container"> 
        {% for data in status %}
            <div class="kotak" style="padding-top: 15px">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="media" style="padding: 40px">
                            <div class="media-left ">
                                <!-- <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-circle" style="width:60px"> --><!--foto nanti diganti dgn foto di hal profile-->
                                <span class="glyphicon glyphicon-user pull-left"></span>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><strong>{{profile_name}}</strong> <small><i>Posted on {{data.created_date}}</i></small></h4><!--nama nanti diganti dgn nama di hal profile-->
                                <p>{{data.status}}</p>
                            </div>
                        </div>
                    </div>
                    <!-- Tombol delete -->
                    <div class="col-md-4">
                        <a href="{% url 'update-status:delete' data.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-danger text-center">
            <strong>Oops!</strong> Belum ada status.
        </div>
    {% endif %}
{% endblock %}